src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields = "username", message = "User with this username already exists")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lastName;

    /**
     * @Assert\Email()
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @Assert\LessThan("today")
     * @ORM\Column(type="date", nullable=true)
     */
    private $dayOfBirth;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="user", cascade={"all"}, orphanRemoval=true)
     */
    private $Addresses;

    /**
     * @ORM\OneToMany(targetEntity=PhoneNumber::class, mappedBy="user", cascade={"all"}, orphanRemoval=true)
     */
    private $PhoneNumbers;

    public function __construct()
    {
        $this->Addresses = new ArrayCollection();
        $this->PhoneNumbers = new ArrayCollection();
        $this->username = sprintf('%08d', hexdec(uniqid()) % 9999999);
    }

    public static function getRoleList(): array
    {
        return ["ROLE_USER" => "User", "ROLE_ADMIN" => "Admin"];
    }

    public function getRolesWithName(): array
    {
        return array_filter(self::getRoleList(), function ($key){
            return in_array($key, $this->getRoles());
        }, ARRAY_FILTER_USE_KEY);
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->createdAt = new \DateTimeImmutable("now");
    }

    /**
     * @ORM\PreUpdate
     * @ORM\PrePersist
     */
    public function onPreUpdate()
    {
        $this->updatedAt = new \DateTimeImmutable("now");
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = array_unique($roles);

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }


    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDayOfBirth(): ?\DateTimeInterface
    {
        return $this->dayOfBirth;
    }

    public function setDayOfBirth(?\DateTimeInterface $dayOfBirth): self
    {
        $this->dayOfBirth = $dayOfBirth;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->Addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->Addresses->contains($address)) {
            $this->Addresses[] = $address;
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->Addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PhoneNumber[]
     */
    public function getPhoneNumbers(): Collection
    {
        return $this->PhoneNumbers;
    }

    public function addPhoneNumber(PhoneNumber $phoneNumber): self
    {
        if (!$this->PhoneNumbers->contains($phoneNumber)) {
            $this->PhoneNumbers[] = $phoneNumber;
            $phoneNumber->setUser($this);
        }

        return $this;
    }

    public function removePhoneNumber(PhoneNumber $phoneNumber): self
    {
        if ($this->PhoneNumbers->removeElement($phoneNumber)) {
            // set the owning side to null (unless already changed)
            if ($phoneNumber->getUser() === $this) {
                $phoneNumber->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/BackendController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserNewType;
use App\Form\UserSearchType;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/backend")
 */
class BackendController extends AbstractController
{
    /**
     * @Route("/", name="backend_index", methods={"GET"})
     */
    public function index(Request $request, UserRepository $userRepository): Response
    {
        $searchForm = $this->createForm(UserSearchType::class, null, ['method' => 'GET']);
        if ($request->get('filter_action') === 'reset') {
            return $this->redirectToRoute('backend_index');
        }
        if ($request->get('filter_action') === 'filter') {
            $searchForm->handleRequest($request);
        }

        return $this->render('backend/index.html.twig', [
            'searchFrom' => $searchForm->createView(),
            'users' => $userRepository->search($searchForm->get('query')->getData()),
        ]);
    }

    /**
     * @Route("/new", name="backend_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordHasherInterface $hasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserNewType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newPassword = $form->get('newPassword')->getData();
            if ($newPassword){
                $user->setPassword($hasher->hashPassword($user, $newPassword));
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('backend_index');
        }

        return $this->render('backend/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="backend_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, UserPasswordHasherInterface $hasher, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newPassword = $form->get('newPassword')->getData();
            if ($newPassword){
                $user->setPassword($hasher->hashPassword($user, $newPassword));
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('backend_index');
        }

        return $this->render('backend/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="backend_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('backend_index');
    }
}

templates/backend/_delete_form.html.twig
<form method="post" action="{{ path('backend_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/backend/_form.html.twig
{{ form_start(form, {attr: { novalidate: true}}) }}
    {{ form_row(form.username) }}
    {{ form_row(form.newPassword) }}
    {{ form_row(form.firstName) }}
    {{ form_row(form.lastName) }}
    {{ form_row(form.email) }}
    {{ form_row(form.dayOfBirth) }}
    <div class="collection">
        <label>Phone numbers</label>
        <div
                class="row-wrapper"
                data-prototype="{{ _self.phoneNumberRow(form.phoneNumbers.vars.prototype)|e('html_attr') }}"
                data-index="{{ form.phoneNumbers|length }}"
        >
            {% for phoneNumber in form.phoneNumbers %}
                {{ _self.phoneNumberRow(phoneNumber) }}
            {% endfor %}
        </div>
        <a class="btn btn-info add-row" href="#">+ Add phone number</a>
    </div>

    <div class="collection">
        <label>Addresses</label>
        <div
                class="row-wrapper"
                data-prototype="{{ _self.addressRow(form.addresses.vars.prototype)|e('html_attr') }}"
                data-index="{{ form.addresses|length }}"
        >
            {% for address in form.addresses %}
                {{ _self.addressRow(address) }}
            {% endfor %}
        </div>
        <a class="btn btn-info add-row" href="#">+ Add address</a>
    </div>

    {{ form_row(form.roles) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{% macro phoneNumberRow(phoneNumber) %}
    <div class="row collection-row">
        <div class="col-11">
            {{ form_widget(phoneNumber.phoneNumber) }}
        </div>
        <div class="col-1">
            <a href="#" class="btn btn-danger remove-row" >Remove</a>
        </div>
    </div>
{% endmacro %}

{% macro addressRow(address) %}
    <div class="row collection-row">
        <div class="col-11">
            <div class="row">
                <div class="col-2">
                    {{ form_row(address.country) }}
                </div>
                <div class="col-4">
                    {{ form_row(address.city) }}
                </div>
                <div class="col-2">
                    {{ form_row(address.zip) }}
                </div>
                <div class="col-4">
                    {{ form_row(address.street) }}
                </div>
            </div>
        </div>
        <div class="col-1 address-remove-wrapper">
            <a href="#" class="btn btn-danger remove-row" >Remove</a>
        </div>
    </div>
{% endmacro %}

templates/backend/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('backend/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="back-link">
        <a href="{{ path('backend_index') }}">back to list</a>
    </div>

    {{ include('backend/_delete_form.html.twig') }}
{% endblock %}

templates/backend/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <div class="search-form-wrapper">
        {{ form_start(searchFrom, {method: 'get', attr: { novalidate: true}}) }}

        {{ form_label(searchFrom.query, 'Users search') }}
        {{ form_widget(searchFrom.query, {'attr': {'placeholder': 'Query'}}) }}
        <div class="search-tip">
            Search tip: The percent matches any group of characters. You could search for "heat*" and find "heated,"
            "heating," and "heats."
        </div>
        <button type="submit" name="filter_action" value="filter" class="btn btn-primary">Search</button>
        <button type="submit" name="filter_action" value="reset" class="btn btn-danger">Reset</button>
        {{ form_end(searchFrom) }}

    </div>

    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Day of birth</th>
                <th>Roles</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody class="table-striped">
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.dayOfBirth ? user.dayOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ user.getRolesWithName | join(', ') }}</td>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('backend_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('backend_new') }}">Create new</a>
{% endblock %}

templates/backend/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('backend/_form.html.twig') }}
    <div class="back-link">
        <a href="{{ path('backend_index') }}">back to list</a>
    </div>
{% endblock %}